apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation-app
  namespace: default
  labels:
    app: simulation-app
    cost-center: engineering
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simulation-app
  template:
    metadata:
      labels:
        app: simulation-app
        cost-center: engineering
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          # INTENTIONALLY OVER-PROVISIONED
          # This app needs ~10m CPU and ~20Mi Memory
          # We are requesting 100x that amount to simulate waste
          requests:
            cpu: "1000m"   # 1 vCPU
            memory: "2Gi"  # 2 GB RAM
          limits:
            cpu: "2000m"
            memory: "4Gi"
