apiVersion: v1
kind: Namespace
metadata:
  name: kubecost
  labels:
    name: kubecost
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubecost-cost-analyzer
  namespace: kubecost
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecost-cost-analyzer
  namespace: kubecost
  labels:
    app: cost-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cost-analyzer
  template:
    metadata:
      labels:
        app: cost-analyzer
    spec:
      serviceAccountName: kubecost-cost-analyzer
      containers:
      - name: cost-analyzer-frontend
        image: gcr.io/kubecost1/frontend:prod-1.106.2
        env:
        - name: GET_HOSTS_FROM
          value: dns
        resources:
          requests:
            cpu: 10m
            memory: 55Mi
          limits:
            cpu: 100m
            memory: 256Mi
        ports:
        - containerPort: 9090
          name: frontend
      - name: cost-analyzer-server
        image: gcr.io/kubecost1/server:prod-1.106.2
        resources:
          requests:
            cpu: 100m
            memory: 55Mi
          limits:
            cpu: 500m
            memory: 1Gi
        env:
        - name: PROMETHEUS_SERVER_ENDPOINT
          value: http://prometheus-server.kubecost.svc.cluster.local
        - name: CLOUD_PROVIDER_API_KEY
          valueFrom:
            secretKeyRef:
              name: kubecost-secrets
              key: cloud-provider-api-key
        - name: CLUSTER_ID
          value: cluster-one
        - name: CUSTOM_LABELS
          value: "team,project"
        ports:
        - containerPort: 9003
          name: server
---
apiVersion: v1
kind: Service
metadata:
  name: kubecost-cost-analyzer
  namespace: kubecost
  labels:
    app: cost-analyzer
spec:
  selector:
    app: cost-analyzer
  type: ClusterIP
  ports:
  - name: service
    port: 9090
    targetPort: 9090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubecost-ingress
  namespace: kubecost
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - host: kubecost.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubecost-cost-analyzer
            port:
              number: 9090
---
apiVersion: v1
kind: Secret
metadata:
  name: kubecost-secrets
  namespace: kubecost
type: Opaque
data:
  # Base64 encoded API key - replace with your actual key
  # echo -n "your-api-key" | base64
  cloud-provider-api-key: <base64-encoded-api-key>